### ISSUE TITLE
Manifest file

### ISSUE THREAD

**Issue by hjstn** [remixer-dec/node-unnpk#1]
I just discovered this project and it helped me a lot with decompiling Terminator2, but I couldn't locate any manifest files as mentioned in the README. I've tried checking both the apk file itself as well as packet capturing game startup.

Could you please share where you had obtained the manifest from in your case?

**Comment by remixer-dec** [comment]
In my case (RulesOfSurvival, which as I understand, is a globalized version of Terminator2) I was able to get it via packet capturing. I looked the game you're talking about and looks like they changed something (and also there is a custom certificate downloaded) or this was because I used latest version... But I found a way to get it, as it's stored in similar way to ROS and also you can still capture it in [older ](https://h45.gdl.netease.com/zjz_netease_17173_cpt2_dev_1.104236.104289.apk) version.
So, I got manifest for updated resources, which are different from ones of the latest apk, and I dont know, where to get manifests for original files (for ROS it is_first_android prefix in the link, but ROS has almost all their resources in the cloud, and not inside the apk).
The updated resource list is stored [here](https://h45.update.netease.com/pl/npk_version_11_02_dts_android.plist) and you can capture it even in the latest APK.  
You can find "version" in this file.
All updated files are stored here `https://{gameID}.gph.netease.com/{version}/res/{npk_filename}`
All manifests for them are stored here `https://{gameID}.gph.netease.com/{version}/file_list_res/{npk_filename_without_extension}`
GameID for your game is h45.

For 'assets' and 'script' resources use first link without '/res' and the second one without the last part, as '/file_list_assets' & '/file_list_script'. Scripts seems to be encrypted or encoded or already compiled to raw bytecode.

**Comment by hjstn** [comment]
Thank you so much, the information you provided was immensely helpful. I haven't been able to find the original manifest either but I'll keep looking.

EDIT: Found original manifest. It's at `https://{gameID}.gph.netease.com/{version}/total_list`. In my case it was [here](https://h45.gph.netease.com/180124162359_android/total_list). It's a zlib compressed file.
